### ISSUE TITLE
Cannot establish two way call using this demo

### ISSUE THREAD

**Issue by ArondeParon** [daily-demos/call-object-react#19]
# Expected behavior

I expect to be able to join establish a two way call with two different browser sessions.

# Describe the bug (unexpected behavior)

When cloning this demo locally, I only get a single thumbnail, but joining the call with more than one person does not work.
Could it be that the hosted demo runs on a different version of the code?

# Screenshots

![Schermafbeelding 2021-07-08 om 12 32 41](https://user-images.githubusercontent.com/7697/124907984-1b1a1400-dfe9-11eb-8bf6-95e91d1b3087.png)

# System information

- Device: Macbook Pro
- OS, version: MacOS Big Sur
- Browser, version: Chrome 91

# Additional context

- When using Daily prebuilt, using my room URL, I can set up a two way call without any problems.

**Comment by kimberleejohnson** [comment]
Hi, @ArondeParon! Thanks for the tag. We work across timezones at Daily, and it looks like my colleague Jon has already been in touch and is able to help here. I'll work with him to make sure we update this repo once we've gotten to the bottom of this. Thanks again!

**Comment by ArondeParon** [comment]
🙊 

It turned out I had my room set to "private", which obviously does not work without setting a token.

Thanks for helping, especially @jptaylor who took the time to walk through this 👍
