### ISSUE TITLE
Unhandled Rejection (Error): property 'url': url should be a string

### ISSUE THREAD

**Issue by nikhilkaimal** [daily-demos/call-object-react#21]
![Screenshot 2021-07-12 215413](https://user-images.githubusercontent.com/32287334/125324752-d16d5880-e35d-11eb-9f84-7aab54af0063.png)

**Comment by kimberleejohnson** [comment]
Hi, @nikhilkaimal! I typically see this error when there are still a few steps left to setup the demo to run locally. Could you please give us a bit more information about how you're running the demo? Thank you!

**Comment by kimberleejohnson** [comment]
Thanks, @nikhilkaimal! There's one more step to get this demo up and running locally (outlined in the [README](https://github.com/kimberleejohnson/call-object-react/blob/main/README.md)): 
- Add the Daily room URL you created to [line 31 of api.js](https://github.com/kimberleejohnson/call-object-react/blob/8da9df5db4c0440a12d9001ad680f32a380b5709/src/api.js#L30), and follow the comment's instructions.

Please let me know if this solves your issue? If you need help creating a Daily account and room, [these instructions](https://help.daily.co/en/articles/4202139-creating-and-viewing-rooms) might be useful.

**Comment by nikhilkaimal** [comment]
yes it worked when I added the daily room url
