### ISSUE TITLE
Screenception when sharing screen

### ISSUE THREAD

**Issue by nikhilkaimal** [daily-demos/call-object-react#23]
![Screenshot (118)](https://user-images.githubusercontent.com/32287334/125575951-ecb20ad7-3d07-45fa-a52d-ce4f8dbdf938.png)

**Comment by jessmitch42** [comment]
When the call UI itself is what's being shared, it will create an infinite loop. You just need to share the window or tab you intend to share with call participants. 🙂 
Closing this issue.
