### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by vipyne** [daily-demos/call-object-react#26]
`open an Issue` link in [contributing and feedback](https://github.com/daily-demos/call-object-react/blob/main/README.md#contributing-and-feedback) is broken. It should point to [here](https://github.com/daily-demos/call-object-react/issues) I believe.

**Comment by jessmitch42** [comment]
Updated [here](https://github.com/daily-demos/call-object-react/pull/32), thanks for posting 😊
